baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Community, a Hugo Theme"
themesdir = "../../"
theme = "community"
enableGitInfo = true
disqusShortname = "hugo-community"
paginate = 15
defaultContentLanguage = "en"

[params]
  author = "Chris Reddington"
  homepage_speakers = 6
  github = "chrisreddington"
  twitter = "reddobowen"
  [params.facebook]
    app_id = ""
    admins = ""
  [params.home]
    [params.home.jumbotron]
      heading = "Community - The community theme for hugo"
      text = "Welcome to our little community, we hope that you like it here. We're an open and inclusive environment, dedicated to help each other learn and grow. We would love your help to continue growing our community. Please explore our page to find more details!"
      buttonText = "Contact"
      buttonUrl = "/"
  [params.footer]
    copyright = "Copyright © 2020 Your Name Here."
    [[params.footer.contacts]]
      key = "email"
      value = "hello@somewhere.com"

#####
# Adjusting to make as private as possible, while not compromising on features that users would likely expect.
# https://gohugo.io/about/hugo-and-gdpr/
#####
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = true
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[taxonomies]
    speaker = "speakers"
    topic = "topics"
    tag = "tags"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1