#####
# Configuration File
# If contributing changes into the exampleSite configuration file, then please observe a few points make your contributions in line with these standards -
# The yaml has been grouped into sections for easier readability.
# Within sections, the properties have been sorted in alphabetical order to ease with maintainability/scanning through information.
#####

#####
# Core hugo configuration.
# You are free to edit these. However, note the 
#####
baseURL: "http://localhost:1313"    # The BaseURL of the hugo website, as shown at https://gohugo.io/getting-started/configuration/#all-configuration-settings
defaultContentLanguage: "en"        # Default content to be used across the site.
disqusShortname: "hugo-community"   # If you wish to use disqus, then
enableGitInfo: true                 # Recommended to keep this enabled. If you are source controlling your repository, then it will allow hugo to determine when pages were last edited, and populate the lastMod property of the page. Otherwise, for the "last edited" functionality to work, relies upon you manually populating the lastMod frontmatter on your content pages.
languageCode: "en-us"               # The default language code for the website. The theme is capable of multi-lingual support. You just need to add additional languages to the config file, and then ensure the appropriate language-code suffixes are set in the file extensions for content.
theme: "hugo-community"                  # Name of the theme. Unless you decide to change themes, you should not change this.
themesdir: "../../"                 # Where the theme directory is stored. If you move the theme directory, you need to update this setting.
title: "Community, a Hugo Theme"    # Title of the site. This will update the title in the Navigation Menu and all <title> tags across the site.
paginate: 15                        # The number of results to be showed by pagination. Configure this as you prefer. As most views display 3 items per page, we have opted for 15 as a multiple of 3.

####
# Menu
# This is the information for the site menus
#####

menu:

  ####
  # The below is an example configuration for a site that has many groups, i.e. a platform for a type of community
  ####
  mainmulti:
    - name: "Home"
      weight: 1
      url: "/"
    - name: "Groups"
      weight: 2
      url: "/groups"
    - name: "Events"
      weight: 3
      url: "/events"
    - name: "Speakers"
      weight: 4
      url: "/speakers"
    - name: "Community"
      weight: 5
      url: "/community"

  ####
  # The below is an example configuration for a site that has a single group
  ####
  mainsingle:
    - name: "Home"
      weight: 1
      url: "/"
    - name: "Group"
      weight: 2
      url: "/group"
    - name: "Events"
      weight: 3
      url: "/events"
    - name: "Speakers"
      weight: 4
      url: "/speakers"
    - name: "Community"
      weight: 5
      url: "/community"

      
  ####
  # The below is an example configuration for a site that has many groups, i.e. a platform for a type of community
  ####
  footermulti:
    - name: "Home"
      weight: 1
      url: "/"
    - name: "Groups"
      weight: 2
      url: "/groups"
    - name: "Events"
      weight: 3
      url: "/events"
    - name: "Speakers"
      weight: 4
      url: "/speakers"
    - name: "Community"
      weight: 5
      url: "/community"

  ####
  # The below is an example configuration for a site that has a single group
  ####
  footersingle:
    - name: "Home"
      weight: 1
      url: "/"
    - name: "Group"
      weight: 2
      url: "/group"
    - name: "Events"
      weight: 3
      url: "/events"
    - name: "Speakers"
      weight: 4
      url: "/speakers"
    - name: "Community"
      weight: 5
      url: "/community"


#####
# Community Theme Parameters
# These are parameters specifically for changing the functionality of the community theme.
# We recommend you adjust these as needed.
#####
params:
  author:  "Chris Reddington"         # Required: This is required for SEO purposes. Please set this appropriately. This is used in the layout/partials/seo/meta.html file.
  disqus_enabled: true                # Boolean to determine whether disqus is enabled on this site. If true, you also need to set the disqusShortname property in the config above.
  facebook:                           # Optional: The information in this section can help with your SEO, and is used in the layout/partials/seo/meta.html file.
    app_id: ""
    admins: ""
  footer:                             # Information relating to the footer area of your site.
    copyright: "Copyright © 2020 Your Name Here."
    contacts:                         # This is an array. To add additional contact methods, just add additional key/value pairs (note the - in front of the key, to denote that this is a new element in the array).
       - key: "email"
         value: "hello@somewhere.com"
  github: "chrisreddington"           # Optional: The information in this section can help with your SEO, and is used in the layout/partials/seo/meta.html file.
  github_repo: "https://github.com/chrisreddington/hugo-community"     #Used within the "Last Edited" information on the page
  github_repo_subfolder: "exampleSite/"     #Used within the "Last Edited" information on the page
  home:                                 # Information relating to the configuration of your homepage.
    jumbotron:                        # Information relating to the jumbotron on your homepage.
      heading: "Community - The community theme for hugo"
      text: "Welcome to our little community, we hope that you like it here. We're an open and inclusive environment, dedicated to help each other learn and grow. We would love your help to continue growing our community. Please explore our page to find more details!"
      buttonText: "Contact"
      buttonUrl: "/"
    speakers: 6                       # Number of speakers to show on the homepage. This list is shuffled. If running as pre-built static content, it will be newly sorted on each new build of your website. If running as a server, then this should be on page load.
  site_mode: "single"                  # single, multi
  show_last_updated: true             # Boolean on whether the last_updated banner should be shown site-wide.
  twitter: "reddobowen"               # Optional: The information in this section can help with your SEO, and is used in the layout/partials/seo/meta.html file.

#####
# Required
# The below are required for taxonomies to function correctly in Hugo.
# Please do not remove the ones that are already set.
# If you decide to update the theme and add additional taxonomies, please add to the below.
#####
taxonomies:
    topic: "topics"
    tag: "tags"
    communityType: "communityTypes"

#####
# Optional - Change at your own discretion.
# Adjusting to make as private as possible, while not compromising on features that users would likely expect.
# https://gohugo.io/about/hugo-and-gdpr/
#####
privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: true
    simple: false
  vimeo:
    disable: true
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true


#####
#####
outputFormats:
  manifest:
    name: "manifest"
    baseName: "manifest"
    mediaType: "application/json"
    notAlternative: "true"
outputs:
  home: 
    - "HTML"
    - "MANIFEST"