#####
#
# Configuration File
# If contributing changes into the exampleSite configuration file, then please 
# observe a few points make your contributions in line with these standards -
#
# 1. The yaml has been grouped into sections for easier readability.
# 2. Within sections, the properties have been sorted in alphabetical order to ease with 
#    maintainability/scanning through information.
#
#####

#####
# Core hugo configuration.
# You are free to edit these. However, note the 
#####

baseURL:                  "http://localhost:1313"
defaultContentLanguage:   "en"
disqusShortname:          "hugo-community"
enableGitInfo:            true
languageCode:             "en-us"
theme:                    "hugo-community"
themesdir:                "../../"
title:                    "Community, a Hugo Theme"
paginate:                  15

####
#
# Mode: Multi Group, Many Events
#
# Use-cases: A website that is a "platform" for many local groups,communities. E.g. showing all of the  groups for a certain technology that are within a given country.
#
####

menu:
  main:
    - name: "Home"
      weight: 1
      url: "/"
    - name: "Groups"
      weight: 2
      url: "/groups"
    - name: "Events"
      weight: 3
      url: "/events"
    - name: "Speakers"
      weight: 4
      url: "/speakers"
    - name: "Community"
      weight: 5
      url: "/community"
  footer:
    - name: "Home"
      weight: 1
      url: "/"
    - name: "Groups"
      weight: 2
      url: "/groups"
    - name: "Events"
      weight: 3
      url: "/events"
    - name: "Speakers"
      weight: 4
      url: "/speakers"
    - name: "Community"
      weight: 5
      url: "/community"

#####
#
# Community Theme Parameters
#
# These are parameters specifically for changing the functionality of the community theme.
# We recommend you adjust these as needed.
#
#####

params:
  author:                            "Chris Reddington"
  disqus_enabled:                    true 
  facebook:
    app_id: ""
    admins: ""
  footer:
    copyright:                        "Copyright © 2020 Your Name Here."
    contacts:                         
       - key: "email"
         value: "hello@somewhere.com"
  github:                           "chrisreddington"
  github_repo:                      "https://github.com/chrisreddington/hugo-community"
  github_repo_subfolder:            "exampleSite/"    
  home:
    events:                         3
    jumbotron:
      heading:                      "Community - The community theme for hugo"
      text:                         "Welcome to our little community, we hope that you like it here. We're an open and inclusive environment, dedicated to help each other learn and grow. We would love your help to continue growing our community. Please explore our page to find more details!"
      buttonText:                   "Contact"
      buttonUrl:                    "/"
    speakers:                       6
  group_configuration:              "multi"
  event_configuration:              "multi"
  show_last_updated:                true
  twitter:                          "reddobowen"

#####
#
# Site Required Settings
#
# The below are required for taxonomies to function correctly in Hugo, as well as the
# manifest.json to be generated for the Progress Web App Functionality.
#
# Please do not remove the taxonomies that are already set.
# If you decide to update the theme and add additional taxonomies, please add to the below.
#
#####

taxonomies:
    topic:                          "topics"
    tag:                            "tags"
    communityType:                  "communityTypes"
outputFormats:
  manifest:
    name:                           "manifest"
    baseName:                       "manifest"
    mediaType:                      "application/json"
    notAlternative:                 "true"
outputs:
  home: 
    - "HTML"
    - "MANIFEST"

#####
#
# Site Privacy Settings
#
# Optional - Configure these settings at your own discretion. These settings are built-in to  
# hugo, and allow you to enable/disable options relating to privacy 
# across platforms.
#
# https://gohugo.io/about/hugo-and-gdpr/
#
#####

privacy:
  disqus:
    disable:                        false
  googleAnalytics:
    anonymizeIP:                    true
    disable: false
    respectDoNotTrack:              true
    useSessionStorage:              false
  instagram:
    disable:                        false
    simple:                         false
  twitter:
    disable:                        false
    enableDNT:                      true
    simple:                         false
  vimeo:
    disable:                        true
    enableDNT:                      false
    simple:                         false
  youtube:
    disable:                        false
    privacyEnhanced:                true