name: Lighthouse
on: [push, pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.79.0"
          extended: true

      - name: Build site
        run: hugo --minify --theme "../" --baseURL "/"
        working-directory: "./exampleSite"

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v2
+       env:
+         LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
        with:
          configPath: "./lighthouserc.json"
          temporaryPublicStorage: true
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage